# auth 配置
spring:
  security:
    user:
      name: admin
      password: 123456
  # 数据源
  datasource:
    # mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    # druid 数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化时建立物理连接的个数,初始化发生在显示调用init方法,或者第一次getConnection时
    initialSize: 2
    # 最小连接池数量
    minIdle: 1
    # 最大连接池数量
    maxActive: 10
    # 配置获取连接等待超时的时间
    maxWait: 10000
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 30000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 验证连接有效与否的SQL,不同的数据配置不同
    validationQuery: select 1
    # 建议配置为true,不影响性能,并且保证安全性
    # 申请连接的时候检测,如果空闲时间大于
    # timeBetweenEvictionRunsMillis，
    # 执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    # 这里建议配置为TRUE，防止取到的连接不可用
    testOnBorrow: true
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 是否缓存preparedStatement，也就是PSCache。
    # PSCache对支持游标的数据库性能提升巨大，比如说oracle。
    # 在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
    # 作者在5.5版本中使用PSCache，通过监控界面发现PSCache有缓存命中率记录，
    # 该应该是支持PSCache。
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 属性类型是字符串，通过别名的方式配置扩展插件，
    # 常用的插件有：
    # 监控统计用的filter:stat
    # 日志用的filter:log4j
    # 防御sql注入的filter:wall
    filters: stat
    # 访问的用户名
    loginUsername: ason
    # 访问的密码
    loginPassword: ason

# 配置服务端口
server:
  port: 8788

# 多个节点高可用服务注册中心
eureka:
  instance:
    ip-address: localhost
    instance-id: ${eureka.instance.ip-address}:${server.port}
    # 上报ip,使注册中心的其它服务地址正确
    hostname: ${eureka.instance.ip-address}
    # 显示IP地址
    prefer-ip-address: true
    # 服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 5
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 10
  client:
    # 刷新服务列表缓存
    registry-fetch-interval-seconds: 5
    # 指定服务注册中心地址
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/



