# gateway 配置
spring:
  security:
    user:
      name: admin
      password: 123456
  cloud:
    gateway:
      discovery:
        locator:
          # 开启服务发现路由规则
          enabled: true
          # 当注册中心为eureka时,设置为true表示开启用小写的serviceId进行基于服务路由的转发,若不配置,默认大写访问,否则会报404
          lower-case-service-id: true
      routes:
        # 这个路由的唯一id,不定义的话为一个uuid
      - id: consumer
        # http请求为lb://前缀 + 服务id,ws请求为lb:ws://前缀 + 服务id,表示将请求负载到哪一个服务上
        uri: lb://consumer
        # 表示这个路由的请求匹配规则,只有符合这个规则的请求才会走这个路由,为一个数组,每个规则为并且的关系.
        # 有After,Before,Between,Cookie,Header,Host,Method,Path,Query,RemoteAddr,
        predicates:
        # =左右不能有空格
        # 通过 Path 匹配
        - Path=/consumer/**
        # 请求转发前的filter,为一个数组.常用的有Hystrix断路由,RequestRateLimiter限流,StripPrefix截取请求url
        filters:
        # =左右不能有空格
        - RewritePath=/consumer/(?<path>.*), /$\{path}
        - StripPrefix=1
      - id: ribbon
        uri: lb://ribbon
        predicates:
        - Path=/ribbon/**
        filters:
        - RewritePath=/ribbon/(?<path>.*), /$\{path}
        - StripPrefix=1

# 配置服务端口
server:
  port: 8766

# Hystrix GatewayFilter Factory
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000









