# zuul 配置
spring:
  security:
    user:
      name: admin
      password: 123456

# 配置服务端口
server:
  port: 8766

# 多个节点高可用服务注册中心
eureka:
  instance:
    ip-address: localhost
    instance-id: ${eureka.instance.ip-address}:${server.port}
    # 上报ip,使注册中心的其它服务地址正确
    hostname: ${eureka.instance.ip-address}
    # 显示IP地址
    prefer-ip-address: true
    # 服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 5
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 10
  client:
    # 刷新服务列表缓存
    registry-fetch-interval-seconds: 5
    # 指定服务注册中心地址
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/

zuul:
  # 版本号
#  prefix: /v1
  routes:
    consumerApi:
      path: /consumer/**
      serviceId: consumer
    ribbonApi:
      path: /ribbon/**
      serviceId: ribbon
  # 是否开启路由重试
#  retryable: true

