# demo测试服务全局配置
spring:
  application:
    name: demo-server

server:
  port: 8083

# 多个节点高可用服务注册中心
eureka:
  instance:
    # 上报ip,使注册中心的其它服务地址正确
    hostname: localhost
    # 显示IP地址
    prefer-ip-address: true
    # 服务刷新时间配置，每隔这个时间会主动心跳一次
#    lease-renewal-interval-in-seconds: 30
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
#    lease-expiration-duration-in-seconds: 90
  client:
    # 刷新服务列表缓存
#    registry-fetch-interval-seconds: 30
    # 指定服务注册中心地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/




